fix advanceBy
lavalibs/lavaqueue pull request #3
Opened 2019-08-13 05:49 UTC by csuvajit

2019-08-14 15:25 UTC, Dramex approved these changes
that's fix undefined

2019-08-15 12:12 UTC, owenselles approved these changes

2019-08-20 06:58 UTC, appellation requested changes
The type signature of the method should be updated to reflect that it takes a `string | null` instead of `NP | null`.

2019-08-20 15:04 UTC, appellation approved these changes

2019-08-20 15:05 UTC, merged